# Generated by Django 4.2.20 on 2025-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_done',
            field=models.BooleanField(default=False),
        ),
    ]
